deploy_production:
  image: rrpnarola/docker_git_ftp
  stage: deploy
  environment:
    name: production
    url: https://eros.narola.online:551/pma4/vpt/data/filament-skeleton/
  only:
    - eros
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - git config git-ftp.url "ftp://$FTP_DEPLOY_HOST:$FTP_PORT/$FTP_PROJECT"
    #- git config git-ftp.server.port "$FTP_PORT"
    - git config git-ftp.password "$FTP_DEPLOY_PASSWORD"
    - git config git-ftp.user "$FTP_DEPLOY_USER"
    #- git ftp init
    - git ftp push --remote-root /$FTP_PROJECT/ -vv --syncroot $CI_PROJECT_DIR --user $FTP_DEPLOY_USER --passwd $FTP_DEPLOY_PASSWORD ftp://$FTP_DEPLOY_HOST:$FTP_PORT
